language: php
php:
  - 7.0
before_script:
  - cd api/lumen
  - cp .env.development .env
  - composer install
  - php artisan migrate:install
  - php artisan migrate
  - php artisan db:seed
script:
  - "./vendor/bin/phpunit"