language: php
php:
  - 7.0

notifications:
  email: false

before_install:
  - mysql -e 'CREATE DATABASE o2n_test;'

before_script:
  - cd api/lumen
  - cp .env.travis .env
  - composer install
  - php artisan migrate:install
  - php artisan migrate
  - php artisan db:seed

script:
  - "./vendor/bin/phpunit"