language: php
php:
- 7.0

notifications:
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_1f05b5cf6cc2_key -iv $encrypted_1f05b5cf6cc2_iv -in deploy_rsa.enc -out deploy_rsa -d
  - mysql -e 'CREATE DATABASE o2n_test;'

before_script:
  - cd api/lumen
  - cp .env.travis .env
  - composer install
  - php artisan migrate:install
  - php artisan migrate
  - php artisan db:seed

script:
  - "./vendor/bin/phpunit"
