version: '2'

services:
  o2n_lumen:
    container_name: o2n_lumen
    build: api/lumen
    working_dir: /var/www/html/lumen
    volumes:
      - ./api/lumen:/var/www/html/lumen
    environment:
      - "WOOCOMMERCE_CONSUMER_KEY=${WOOCOMMERCE_CONSUMER_KEY}"
      - "WOOCOMMERCE_CONSUMER_SECRET=${WOOCOMMERCE_CONSUMER_SECRET}"
      - "PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}"
      - "PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}"
      - "YOUTUBE_API_KEY=${YOUTUBE_API_KEY}"

  o2n_wordpress:
    container_name: o2n_wordpress
    build: api/wordpress
    working_dir: /var/www/html/wordpress
    volumes:
      - ./api/wordpress:/var/www/html/wordpress
    environment:
      - "ENV=${ENV}"
      - "API_HOST=${API_HOST}"
      - "WORDPRESS_DB_NAME=wordpress"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_HOST=o2n_wordpress_db:3306"
      - "WORDPRESS_DB_PASSWORD=password"

  o2n_nginx:
    container_name: o2n_nginx
    build: images/nginx/development
    volumes_from:
      - o2n_lumen
      - o2n_wordpress
    volumes:
      - ./logs:/var/www/logs
      - ./config/certs:/var/www/letsencrypt
      - ./client/dist:/var/www/html/client
    ports:
      - 80:80
      - 443:443

  o2n_lumen_db:
    container_name: o2n_lumen_db
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=password"

  o2n_wordpress_db:
    container_name: o2n_wordpress_db
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"

  o2n_client:
    container_name: o2n_client
    build: client
    working_dir: /var/www/html/client
    command: "sh -c 'yarn && npm run dev'"
    volumes:
      - ./client:/var/www/html/client
    ports:
      - "8081:8080"
