version: '2'

services:
  o2n_lumen:
    container_name: o2n_lumen
    build: images/lumen
    working_dir: /var/www/html/lumen
    volumes:
      - ./api/lumen:/var/www/html/lumen
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=o2n_lumen_db"

  o2n_wordpress:
    container_name: o2n_wordpress
    build: images/wordpress
    working_dir: /var/www/html/wordpress
    volumes:
      - ./api/wordpress:/var/www/html/wordpress
    environment:
      - "WORDPRESS_DB_HOST=o2n_wordpress_db:3306"
      - "WORDPRESS_DB_PASSWORD=password"

  o2n_nginx:
    container_name: o2n_nginx
    build: images/nginx
    volumes_from:
      - o2n_lumen
      - o2n_wordpress
      - o2n_client
    volumes:
      - ./logs:/var/www/logs
    ports:
      - 80:80

  o2n_lumen_db:
    container_name: o2n_lumen_db
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "33061:3306"

  o2n_wordpress_db:
    container_name: o2n_wordpress_db
    image: mariadb:latest
    environment:
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - "33062:3306"

  o2n_client:
    container_name: o2n_client
    build: images/client
    working_dir: /var/www/html/client
    command: npm run dev
    volumes:
      - ./client:/var/www/html/client
    ports:
      - "8081:8080"
